from os import path
#algumas variaveis utilizadas em varios lugares

#PATH PARA CONSEEGUIR ACESSAR AS IMAGENS E AS ANIMAÇÕES
IMG_DIR=path.join(path.dirname(__file__),'assets', 'img')
ANI_DIR=path.join(path.dirname(__file__),'assets', 'animacao')

#TAMANHO DA TELA (PODE ALTERAR, NAO VAI ZUAR TAMANHO DE NADA)
#TUDO TA FEITO COM BASE NESSAS VARIAVEIS
WIDTH=1200
HEIGHT=800

#USADO PARA CONTRALAR A QUANTIDADE DE VEZES Q A TELA SE REENDERIZA
FPS=60

#USADO PARA ALTERAR NO JOGO FINAL
#E ENTRAR NOS OUTROS ARQUIVOS
MENU=0
ENCERRAR=2
LUTA=1
TELA=3
VITORIA="VITORIA"
DERROTA="DERROTA"
EMPATE="EMPATE"

#USA NO LUTA, PARA DEIXAR TUDO EM ORDEM
#VARIAVEL DE ESTADO
PODE_ATACAR = 'PODE_ATACAR'
ATACANDO = 'ATACANDO'
ANIMACAO_ATAQUE = 'ANIMACAO_ATAQUE'
SCRIPT_ATAQUE = 'SCRIPT_ATAQUE'
CATACANDO = 'CATACANDO'
ANIMACAO_CATAQUE = 'ANIMACAO_CATAQUE'
SCRIPT_CATAQUE = 'SCRIPT_CATAQUE'